kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build
  settings:
    # registry: docker.io
    repo: pavansa/my-app-new
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
